version: "3.8"

services:
  frontend:
    container_name: app
    build: .
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - BACKEND_URL=http://backend:3001
    volumes:
      - .:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    external: true
