version: "3.8"

services:
  radiotech-frontend:
    container_name: radiotech-frontend
    build: .
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - app-network

networks:
  app-network:
    external: true
