version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: node app.js
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
